# Generated by Django 4.1.1 on 2022-09-22 15:06

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRemote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Тип работы',
                'verbose_name_plural': 'Типы работы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='JobStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Категория учеников',
                'verbose_name_plural': 'Категории учеников',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название типа занятости')),
            ],
            options={
                'verbose_name': 'Тип занятости',
                'verbose_name_plural': 'Типы занятости',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='JobViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name': 'Просмотр вакансии',
                'verbose_name_plural': 'Просмотры вакансий',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название вакансии')),
                ('contacts', models.CharField(max_length=150, verbose_name='Контакты')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание вакансии')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Город')),
                ('location_id', models.TextField(blank=True, verbose_name='ID города')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('job_types', models.ManyToManyField(blank=True, related_name='jobtype_jobs', to='jobs.jobtype', verbose_name='Типы зантости')),
                ('remote', models.ManyToManyField(blank=True, related_name='jobremote_jobs', to='jobs.jobremote', verbose_name='Тип работы')),
                ('role', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='employeerole_jobs', to='employees.employeerole', verbose_name='Роль')),
                ('students', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobstudents_jobs', to='jobs.jobstudents', verbose_name='Ученики')),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('views', models.ManyToManyField(blank=True, editable=False, related_name='view_jobs', to='jobs.jobviews', verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
