# Generated by Django 4.1.1 on 2022-09-22 15:06

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название категории, до 50 символов', max_length=50, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория статей',
                'verbose_name_plural': 'Категории статей',
            },
        ),
        migrations.CreateModel(
            name='PostViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name': 'Просмотр статьи',
                'verbose_name_plural': 'Просмотры статей',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок поста, до 150 символов', max_length=150, verbose_name='Заголовок')),
                ('abstract', models.CharField(blank=True, help_text='Небольшое превью к новости, максимум 300 символов', max_length=300, verbose_name='Реферат')),
                ('image', models.ImageField(blank=True, help_text='Картинка для отображения рядом с новостью', upload_to='images/%Y/%m/%d/', verbose_name='Изображение')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Текст поста в разметке HTML', verbose_name='Текст')),
                ('attached_files', models.FileField(blank=True, help_text='Прикрепленные к новости файлы', upload_to='files/%Y/%m/%d/', verbose_name='Прикрепленные файлы')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликована')),
                ('authors', models.ManyToManyField(related_name='author_news', to=settings.AUTH_USER_MODEL, verbose_name='Авторы')),
                ('categories', models.ManyToManyField(blank=True, help_text='Категории поста', related_name='category_news', to='news.newscategory', verbose_name='Категории')),
                ('views', models.ManyToManyField(blank=True, editable=False, related_name='view_news', to='news.postviews', verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
