# Generated by Django 4.1.1 on 2022-09-22 15:06

import ckeditor_uploader.fields
from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', ckeditor_uploader.fields.RichTextUploadingField(help_text='Текст о себе в разметке HTML', verbose_name='О себе')),
                ('resume_file', models.FileField(blank=True, help_text='Файл с резюме', upload_to=employees.models.user_resume_path, verbose_name='Файл с резюме')),
                ('portfolio', models.TextField(blank=True, verbose_name='Ссылки на работы')),
                ('rating', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=3, verbose_name='Рейтинг')),
                ('times_rated', models.SmallIntegerField(default=0, editable=False, verbose_name='Кол-во оценок')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('approved', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('contacts', models.CharField(max_length=150, verbose_name='Контакты')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Город')),
                ('location_id', models.TextField(blank=True, verbose_name='ID города')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='EmployeeViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name': 'Просмотр',
                'verbose_name_plural': 'Просмотры',
            },
        ),
    ]
